# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# Handle requirements required to build your docs
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
